### ISSUE TITLE
Troubleshooting - INSTALLER ERROR - An error has occurred during the installation process. Look at the logs for more details.

### ISSUE THREAD

**Issue by TheSnowWight** [starcitizen-lug/knowledge-base#11]
### INSTALLER ERROR
An error has occurred during the installation process. Look at the logs for more details.

![Installer-error](https://user-images.githubusercontent.com/45722564/219851707-01889926-6659-4e77-b4ea-49b1aff9a18d.png)

**How to identify?**
Issue was identified by having lug-helper open while launching StarCitizen from Lutris

**Potential cause**
The installer is unable to create few missing game directories due to missing privileges. Adding directories manually allows the installer to start the download and install process.

**Example error message seen in LUG Helper**
"Error while attempting to create directories with command: \"C:\\Program Files\\Roberts Space Industries\\RSI Launcher\\resources\\installer-support.exe\" --create-installation-directory \"C:\\Program Files\\Roberts Space Industries\\StarCitizen\" --create-installation-directory \"C:\\Program Files\\Roberts Space Industries\\StarCitizen\\LIVE\", Error: User did not grant permission."

**Error message** 
User did not grant permission

**Potential solution**
1. Browse to the directory where the game files exist
2. Manually create folder under **Roberts Space Industries** called **StarCitizen**
3. Under **StarCitizen** create folder called **LIVE**
4. Attempt the download again and it should work as the folders now exist

Path before
/.../drive_c/Program Files/Roberts Space Industries/

Path after
/.../drive_c/Program Files/Roberts Space Industries/StarCitizen/LIVE

**Comment by the-sane** [comment]
Thanks for the report! Can you confirm that you were trying to install the game using the script from the Lutris website?

If so, this is because the installer from the Lutris website is currently very broken and we're waiting on access to be able to fix it. We released a fixed version of the installer bundled with our Helper, so if you used the latest version of the Helper to install the game you shouldn't have seen this problem. Please let me know if this is the case though.

We also have a note about this on our wiki's news section under Game Updates, marked "(Jan 27, 2023) Fresh installs fail to create needed directories":
https://github.com/starcitizen-lug/knowledge-base/wiki#news

**Comment by TheSnowWight** [comment]
I used the lug-helper to do preflight check and install the launcher. 
Once the launcher was installed I started it from Lutris and pressed download and this is when the error appeared.

I tried to find the issue from the wiki, but as the error message didn't match I missed it.
The issue is identical to the one mentioned in the wiki, so I consider this one a known issue due to the non-default directory path I chose to use! 
Note! I'm installing on a secondary ssd which is mounted under /media/username/drivename/path/to...

Thank you for getting back to me on this and truly great work with the lug, this thing made the install a breeze! :)

**Comment by the-sane** [comment]
Hm, so our bundled installer makes those directories like so:
https://github.com/starcitizen-lug/lug-helper/blob/568f24a15c6cb750cdb376b108fdd461ad51f9ea/lug-lutris-install.json#L73-L75

That should have been working if you used the Helper to do the install. One other person mentioned having this problem not too long ago, but they weren't able to help troubleshoot it.

If you're able to do some testing on another install to help us figure out why that line in our install json didn't work for your setup, that'd be really appreciated. Some thoughts on what you could try if you're able to:
- Maybe the brace expansion doesn't work with your shell? You could try removing that and only specifying the LIVE directory at the end
- What happens if you manually edit the json file to specify the full path to your secondary ssd? Does it still error?

**Comment by TheSnowWight** [comment]
Managed to replicate the issue

Folders are created when using no space in the custom directory name
/media/username/ssd/**Test**

Folders aren't created when using space in the custom directory name
/media/username/ssd/**RSI Test**

Tested by manually specifying the paths containing spaces and the script worked just fine.

**Comment by the-sane** [comment]
Aha! That makes sense actually. Thank you for tracking that down. Can you try changing the line in your json so that the entire path is enclosed in escaped quotes like so:
```
 "command": "mkdir -p \"$GAMEDIR/drive_c/Program Files/Roberts Space Industries/StarCitizen/{LIVE,PTU}\""
```

**Comment by TheSnowWight** [comment]
Tested and works! I also verified the download starts.

Don't you just love using spaces in linux directory paths ;)

**Comment by the-sane** [comment]
Awesome, thanks for testing it!

Fixed in https://github.com/starcitizen-lug/lug-helper/commit/ae9d34e943b3a7c443ba071d6bdbeb0f8b756598
