### ISSUE TITLE
Troubleshoot guide suggestion and opentrack tips & tricks addition

### ISSUE THREAD

**Issue by Priton-CE** [starcitizen-lug/knowledge-base#8]
This is an edit to the current wiki.
It adds
- a troubleshoot guide which aims to improve the troubleshooting process for less experienced linux users
- an entry to the troubleshoot guide on the main page
- a headtracking section on the tips and tricks page

(No biggie if it gets rejected.)

[Home.md](https://github.com/starcitizen-lug/information-howtos/files/9944760/Home.md)
[Tips-and-Tricks.md](https://github.com/starcitizen-lug/information-howtos/files/9944761/Tips-and-Tricks.md)
[Trouble-Shoot-Guide.md](https://github.com/starcitizen-lug/information-howtos/files/9944762/Trouble-Shoot-Guide.md)

**Comment by the-sane** [comment]
Thanks! We discussed this a bit in Discord but I'll put my notes here too:

I added a head tracking section to the tips and tricks page. I don't think setting that up is all that complicated so I kept it simple. But let me know if I'm missing something critical.

As for the rest, here are my suggestions:
- Let's improve the existing issues/solutions page rather than maintaining a separate troubelshooting page with redundant info
- An overview type section at the top with instructions for running lutris in debug mode or access various logs would be useful
- Then perhaps divide that page up into two main sections. A most common issues section, and an other issues section.
- Then we can rearrange the existing content on that page into those two sections rather than duplicating it on other pages

**Comment by the-sane** [comment]
Just dumping some more notes out of my brain for how I think the page should be restructured:

### Troubleshooting Steps
- Tell folks to check the news first, especially nvidia people
- Simple, step by step instructions on opening logs and running lutris in debug mode (native and flatpak)

### Most Common Issues
- copy and paste the most common issues here in some kind of order#6 

### Other Issues
- Move the rest of the issues down here

**Comment by the-sane** [comment]
An attempt was made at organizing the page. Still feels like a big imposing list though.

**Comment by the-sane** [comment]
@Priton-CE You can now submit pull requests against this wiki:
https://github.com/starcitizen-lug/knowledge-base/tree/main/wiki

**Comment by the-sane** [comment]
I've cleaned up the common issues/solutions page, renamed it troubleshooting, and integrated the pieces of your guides where it made sense to include them. Thanks for helping with this!
